# Site wide configuration

title: Matt Berther
locale: en_US
description: Musings of an agile development manager and occasional code monkey
logo: site-logo.png
url: https://matt.berther.io

# Jekyll configuration
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

permalink:   pretty
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import

plugins:
  - jekyll-sitemap

include: [".htaccess"]
exclude: ["*.yml", "package.json", "package-lock.json", "LICENSE", "README.md", 
    "assets/site-logo.pxm", "resume.json", "build.mjs"]

# Site owner
owner:
  name: Matt Berther
  avatar: avatar.png
  email: matt@berther.io
  disqus-shortname: mattberther
  github: mattberther
  stackexchange: https://stackoverflow.com/users/3802812/mattberther
  linkedin: mattberther
  google-verify: CxDTL79fUhDFRymu4PbBvR7kyL4lMUvMstxYH3Zj1eQ
  bing-verify: 64C176A9AD2C4795A89181A62F31EB7F

umami:
  website_id: 26967149-7ab7-49f7-9795-9b599b389319
  script_url: https://cloud.umami.is/script.js

google_fonts:
  - name: "Source Sans Pro"
    weight: "200i,300i,400i,600i,700i,900i,200,300,400,600,700,900"
    weights: "100,300,400,600"
  - name: "Source Code Pro"
    weights: "400,700"
  - name: "Volkhov"
