# Site wide configuration

title: Matt Berther
locale: en_US
description: Musings of an agile development manager and occasional code monkey
logo: site-logo.png
search: true
url: https://matt.berther.io

# Jekyll configuration
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

permalink:   pretty
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

include: [".htaccess"]
exclude: ["*.yml", "Rakefile", "package.json", "package-lock.json",
    "LICENSE", "README.md", "assets/site-logo.pxm",
    "resume.json", "routing-rules.xml", "Gulpfile.js", "Thorfile", "bin"]

# Site owner
owner:
  name: Matt Berther
  avatar: avatar.png
  email: matt@berther.io
  disqus-shortname: mattberther
  twitter: mattberther
  facebook:
  github: mattberther
  stackexchange: https://stackoverflow.com/users/3802812/mattberther
  linkedin: mattberther
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    analytics: UA-44086841-1
    verify: CxDTL79fUhDFRymu4PbBvR7kyL4lMUvMstxYH3Zj1eQ
    ad-client:
    ad-slot:
  bing-verify: 64C176A9AD2C4795A89181A62F31EB7F

google_fonts:
  - name: "Source Sans Pro"
    weight: "200i,300i,400i,600i,700i,900i,200,300,400,600,700,900"
    weights: "100,300,400,600"
  - name: "Source Code Pro"
    weights: "400,700"
  - name: "Volkhov"
